In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
import os
if os.getcwd().endswith('notebooks'):
  os.chdir('..')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from src.training import investigate_predictions, calculate_metrics, load_config, DATA_TIME_INTERVAL

In [ ]:
model_name = '053-pred_horizon_60' # change
config = load_config(model_name)

In [ ]:
model_results = []
for i in range(config['repetitions']):
  X, y_preds, y_trues = investigate_predictions(model_name, iteration=i, split='test')
  for j in [3, 6, 9, 12]:
    model_results.append({'horizon': f'{j * 5} min', **calculate_metrics(y_preds[:, j], y_trues[:, j])})
  model_results.append({'horizon': '5-60 min (5 min steps)', **calculate_metrics(y_preds, y_trues)})
model_results = pd.DataFrame(model_results)
model_results

ðŸ‘‰ loading model 1/3
ðŸ‘‰ loading data
     training samples: 122261
     val samples: 35705
ðŸ‘‰ predicting values
ðŸ‘‰ loading model 2/3
ðŸ‘‰ loading data
     training samples: 122261
     val samples: 35705
ðŸ‘‰ predicting values
ðŸ‘‰ loading model 3/3
ðŸ‘‰ loading data
     training samples: 122261
     val samples: 35705
ðŸ‘‰ predicting values

,horizon,mse,rmse,mape,mae,gmse,grmse
0,0 min,15.602988,3.950062,0.015541,2.286813,19.797079,4.449391
1,0 min,15.602988,3.950062,0.015541,2.286813,19.797079,4.449391
2,0 min,15.602988,3.950062,0.015541,2.286813,19.797079,4.449391
3,0 min,15.602988,3.950062,0.015541,2.286813,19.797079,4.449391
4,5-60 min (5 min steps),164.403366,12.821987,0.053689,7.822863,218.447159,14.779958
5,5 min,58.827904,7.669935,0.034227,4.995700,83.129837,9.117557
6,5 min,58.827904,7.669935,0.034227,4.995700,83.129837,9.117557
7,5 min,58.827904,7.669935,0.034227,4.995700,83.129837,9.117557
8,5 min,58.827904,7.669935,0.034227,4.995700,83.129837,9.117557
9,5-60 min (5 min steps),180.623566,13.439627,0.059677,8.610375,274.897339,16.580029
10,10 min,119.932922,10.951389,0.054096,7.602767,154.594910,12.433620
11,10 min,119.932922,10.951389,0.054096,7.602767,154.594910,12.433620
12,10 min,119.932922,10.951389,0.054096,7.602767,154.594910,12.433620
13,10 min,119.932922,10.951389,0.054096,7.602767,154.594910,12.433620
14,5-60 min (5 min steps),180.812958,13.446671,0.063590,8.799704,234.262161,15.305625

In [19]:
changed_model_results = model_results.copy()
changed_model_results['mape'] = changed_model_results['mape'] * 100
means = changed_model_results.groupby('horizon').mean().round(2)
stds = changed_model_results.groupby('horizon').std().round(2)

table = means.astype(str).add(' Â± ').add(stds.astype(str))
table.columns = table.columns.str.upper()
table = table.rename(columns={'GMSE': 'gMSE', 'GRMSE': 'gRMSE'})
table = table[['RMSE', 'MAPE', 'gRMSE']]
table.index.name = None
table

                                RMSE        MAPE         gRMSE
0 min                     3.95 Â± 0.0  1.55 Â± 0.0    4.45 Â± 0.0
10 min                   10.95 Â± 0.0  5.41 Â± 0.0   12.43 Â± 0.0
5 min                     7.67 Â± 0.0  3.42 Â± 0.0    9.12 Â± 0.0
5-60 min (5 min steps)  13.24 Â± 0.36   5.9 Â± 0.5  15.56 Â± 0.93

In [ ]:
table.to_latex()

'\\begin{tabular}{lll}\n\\toprule\nRMSE & MAPE & gRMSE \\\\\n\\midrule\n13.24 Â± 0.36 & 5.9 Â± 0.5 & 15.56 Â± 0.93 \\\\\n\\bottomrule\n\\end{tabular}\n'